import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { Theme } from '@/types/Theme';

import type { Metadata } from 'next';
import { cookies } from 'next/dist/client/components/headers';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Felipe Rocha',
  description: 'Generated by create next app as my own port',
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const hasDarkModeCookie = cookies().get('theme')?.value === Theme.DARK;

  return (
    <html lang={lang} className={hasDarkModeCookie ? Theme.DARK : undefined}>
      <body className={inter.className}>
        <Header hasDarkModeCookie={hasDarkModeCookie} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
